#!/bin/sh
#
# prime-web
# MIT License
# @doublecompile
# Installs .deb packages and initializes some config

echo "Installing packages."
apt-get update
apt-get install aptitude
aptitude -y safe-upgrade
aptitude install -y --without-recommends nginx ca-certificates \
    python-pip \
    php5-fpm php5-cli php5-gd php5-gmp php5-mcrypt php5-imagick \
    php5-memcached php5-mysqlnd php5-pgsql php5-sqlite php5-curl

echo "Generating DH Parameter file."
openssl dhparam -out "/etc/ssl/dhparam.pem" 2048 2>/dev/null

echo "Installing configuration."
cp conf/nginx.conf /etc/nginx/nginx.conf
cp conf/mime.types /etc/nginx/mime.types
cp conf/ssl.conf /etc/nginx/conf.d/ssl.conf
cp conf/php5-fpm_php.ini /etc/php5/fpm/php.ini
cp conf/php5-cli_php.ini /etc/php5/cli/php.ini

echo "Disabling PHP session cleanup cron job."
sed -i 's/^/#/' /etc/cron.d/php5

service php5-fpm restart
service nginx restart

# All done
echo "Everything is OK!"
