#!/bin/sh
#
# prime-web
# MIT License
# @doublecompile
# Installs .deb packages and initializes some config

echo "Installing packages."
apt-get update
apt-get install aptitude
aptitude -y safe-upgrade
aptitude install -y --without-recommends nginx ca-certificates letsencrypt \
    python-pip \
    php7.0-fpm php7.0-cli php7.0-gd php7.0-gmp php7.0-mcrypt php-imagick php7.0-mbstring \
    php-memcached php7.0-mysql php7.0-pgsql php7.0-sqlite3 php7.0-curl

echo "Generating DH Parameter file."
openssl dhparam -out "/etc/ssl/dhparam.pem" 2048 2>/dev/null

echo "Installing configuration."
cp conf/nginx.conf /etc/nginx/nginx.conf
cp conf/mime.types /etc/nginx/mime.types
cp conf/ssl.conf /etc/nginx/conf.d/ssl.conf
cp conf/php5-fpm_php.ini /etc/php/7.0/fpm/php.ini
cp conf/php5-cli_php.ini /etc/php/7.0/cli/php.ini

echo "Disabling PHP session cleanup cron job."
sed -i 's/^/#/' /etc/cron.d/php

service php7.0-fpm restart
service nginx restart

# All done
echo "Everything is OK!"
