#!/bin/sh

curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent2.sh | sh
td-agent-gem install fluent-plugin-parser
td-agent-gem install fluent-plugin-rewrite-tag-filter
td-agent-gem install fluent-plugin-cloudwatch-logs

echo "# Forward everything to td-agent" > /etc/rsyslog.d/01-forward.conf
echo "*.* @127.0.0.1:42185" >> /etc/rsyslog.d/01-forward.conf
echo "& stop" >> /etc/rsyslog.d/01-forward.conf

myInstanceId=$(curl http://instance-data/latest/meta-data/instance-id)
myNetworkMac=$(curl http://instance-data/latest/meta-data/network/interfaces/macs/)
myVpcId=$(curl http://instance-data/latest/meta-data/network/interfaces/macs/${myNetworkMac}/vpc-id)

mkdir -p /tmp/git
git clone https://gist.github.com/8264a995bf86b1c4129f05673c17feca.git /tmp/git/td-agent
cp /tmp/git/td-agent/td-agent.conf /etc/td-agent/td-agent.conf
sed -i "s/instance-placeholder/$myInstanceId/" /etc/td-agent/td-agent.conf
sed -i "s/vpc-placeholder/$myVpcId/" /etc/td-agent/td-agent.conf

rm -r /tmp/git
